#include <C:\Users\Stefan\Desktop\SDL3Sharp\Libraries/SDL/include/SDL3/SDL.h>
#include <C:\Users\Stefan\Desktop\SDL3Sharp\Libraries/SDL/include/SDL3/SDL_video.h>
#include <C:\Users\Stefan\Desktop\SDL3Sharp\Libraries/SDL/include/SDL3/SDL_version.h>
#include <new>

int (*_0)(unsigned long long, unsigned long long, unsigned long long*) = &::SDL_size_mul_overflow;
int (*_1)(unsigned long long, unsigned long long, unsigned long long*) = &::SDL_size_mul_overflow_builtin;
int (*_2)(unsigned long long, unsigned long long, unsigned long long*) = &::SDL_size_add_overflow;
int (*_3)(unsigned long long, unsigned long long, unsigned long long*) = &::SDL_size_add_overflow_builtin;
SDL_AssertData& (SDL_AssertData::*_4)(SDL_AssertData&&) = &SDL_AssertData::operator=;
SDL_AtomicInt& (SDL_AtomicInt::*_5)(SDL_AtomicInt&&) = &SDL_AtomicInt::operator=;
void (*_6)(void*) = &::_m_prefetch;
float (*_7)(float) = &::SDL_SwapFloat;
SDL_RWops& (SDL_RWops::*_8)(SDL_RWops&&) = &SDL_RWops::operator=;
SDL_AudioSpec& (SDL_AudioSpec::*_9)(SDL_AudioSpec&&) = &SDL_AudioSpec::operator=;
int (*_10)(unsigned int) = &::SDL_MostSignificantBitIndex32;
int (*_11)(unsigned int) = &::SDL_HasExactlyOneBitSet32;
SDL_Color& (SDL_Color::*_12)(SDL_Color&&) = &SDL_Color::operator=;
SDL_FColor& (SDL_FColor::*_13)(SDL_FColor&&) = &SDL_FColor::operator=;
SDL_Palette& (SDL_Palette::*_14)(SDL_Palette&&) = &SDL_Palette::operator=;
SDL_PixelFormat& (SDL_PixelFormat::*_15)(SDL_PixelFormat&&) = &SDL_PixelFormat::operator=;
SDL_Point& (SDL_Point::*_16)(SDL_Point&&) = &SDL_Point::operator=;
SDL_FPoint& (SDL_FPoint::*_17)(SDL_FPoint&&) = &SDL_FPoint::operator=;
SDL_Rect& (SDL_Rect::*_18)(SDL_Rect&&) = &SDL_Rect::operator=;
SDL_FRect& (SDL_FRect::*_19)(SDL_FRect&&) = &SDL_FRect::operator=;
int (*_20)(const SDL_Point*, const SDL_Rect*) = &::SDL_PointInRect;
int (*_21)(const SDL_Rect*) = &::SDL_RectEmpty;
int (*_22)(const SDL_Rect*, const SDL_Rect*) = &::SDL_RectsEqual;
int (*_23)(const SDL_FPoint*, const SDL_FRect*) = &::SDL_PointInRectFloat;
int (*_24)(const SDL_FRect*) = &::SDL_RectEmptyFloat;
int (*_25)(const SDL_FRect*, const SDL_FRect*, const float) = &::SDL_RectsEqualEpsilon;
int (*_26)(const SDL_FRect*, const SDL_FRect*) = &::SDL_RectsEqualFloat;
SDL_Surface& (SDL_Surface::*_27)(SDL_Surface&&) = &SDL_Surface::operator=;
SDL_DisplayMode& (SDL_DisplayMode::*_28)(SDL_DisplayMode&&) = &SDL_DisplayMode::operator=;
SDL_CameraSpec& (SDL_CameraSpec::*_29)(SDL_CameraSpec&&) = &SDL_CameraSpec::operator=;
SDL_GUID& (SDL_GUID::*_30)(SDL_GUID&&) = &SDL_GUID::operator=;
SDL_VirtualJoystickDesc& (SDL_VirtualJoystickDesc::*_31)(SDL_VirtualJoystickDesc&&) = &SDL_VirtualJoystickDesc::operator=;
SDL_GamepadBinding& (SDL_GamepadBinding::*_32)(SDL_GamepadBinding&&) = &SDL_GamepadBinding::operator=;
SDL_Keysym& (SDL_Keysym::*_33)(SDL_Keysym&&) = &SDL_Keysym::operator=;
SDL_PenCapabilityInfo& (SDL_PenCapabilityInfo::*_34)(SDL_PenCapabilityInfo&&) = &SDL_PenCapabilityInfo::operator=;
SDL_Finger& (SDL_Finger::*_35)(SDL_Finger&&) = &SDL_Finger::operator=;
SDL_CommonEvent& (SDL_CommonEvent::*_36)(SDL_CommonEvent&&) = &SDL_CommonEvent::operator=;
SDL_DisplayEvent& (SDL_DisplayEvent::*_37)(SDL_DisplayEvent&&) = &SDL_DisplayEvent::operator=;
SDL_WindowEvent& (SDL_WindowEvent::*_38)(SDL_WindowEvent&&) = &SDL_WindowEvent::operator=;
SDL_KeyboardEvent& (SDL_KeyboardEvent::*_39)(SDL_KeyboardEvent&&) = &SDL_KeyboardEvent::operator=;
SDL_TextEditingEvent& (SDL_TextEditingEvent::*_40)(SDL_TextEditingEvent&&) = &SDL_TextEditingEvent::operator=;
SDL_TextInputEvent& (SDL_TextInputEvent::*_41)(SDL_TextInputEvent&&) = &SDL_TextInputEvent::operator=;
SDL_MouseMotionEvent& (SDL_MouseMotionEvent::*_42)(SDL_MouseMotionEvent&&) = &SDL_MouseMotionEvent::operator=;
SDL_MouseButtonEvent& (SDL_MouseButtonEvent::*_43)(SDL_MouseButtonEvent&&) = &SDL_MouseButtonEvent::operator=;
SDL_MouseWheelEvent& (SDL_MouseWheelEvent::*_44)(SDL_MouseWheelEvent&&) = &SDL_MouseWheelEvent::operator=;
SDL_JoyAxisEvent& (SDL_JoyAxisEvent::*_45)(SDL_JoyAxisEvent&&) = &SDL_JoyAxisEvent::operator=;
SDL_JoyHatEvent& (SDL_JoyHatEvent::*_46)(SDL_JoyHatEvent&&) = &SDL_JoyHatEvent::operator=;
SDL_JoyButtonEvent& (SDL_JoyButtonEvent::*_47)(SDL_JoyButtonEvent&&) = &SDL_JoyButtonEvent::operator=;
SDL_JoyDeviceEvent& (SDL_JoyDeviceEvent::*_48)(SDL_JoyDeviceEvent&&) = &SDL_JoyDeviceEvent::operator=;
SDL_JoyBatteryEvent& (SDL_JoyBatteryEvent::*_49)(SDL_JoyBatteryEvent&&) = &SDL_JoyBatteryEvent::operator=;
SDL_GamepadAxisEvent& (SDL_GamepadAxisEvent::*_50)(SDL_GamepadAxisEvent&&) = &SDL_GamepadAxisEvent::operator=;
SDL_GamepadButtonEvent& (SDL_GamepadButtonEvent::*_51)(SDL_GamepadButtonEvent&&) = &SDL_GamepadButtonEvent::operator=;
SDL_GamepadDeviceEvent& (SDL_GamepadDeviceEvent::*_52)(SDL_GamepadDeviceEvent&&) = &SDL_GamepadDeviceEvent::operator=;
SDL_GamepadTouchpadEvent& (SDL_GamepadTouchpadEvent::*_53)(SDL_GamepadTouchpadEvent&&) = &SDL_GamepadTouchpadEvent::operator=;
SDL_GamepadSensorEvent& (SDL_GamepadSensorEvent::*_54)(SDL_GamepadSensorEvent&&) = &SDL_GamepadSensorEvent::operator=;
SDL_AudioDeviceEvent& (SDL_AudioDeviceEvent::*_55)(SDL_AudioDeviceEvent&&) = &SDL_AudioDeviceEvent::operator=;
SDL_CameraDeviceEvent& (SDL_CameraDeviceEvent::*_56)(SDL_CameraDeviceEvent&&) = &SDL_CameraDeviceEvent::operator=;
SDL_TouchFingerEvent& (SDL_TouchFingerEvent::*_57)(SDL_TouchFingerEvent&&) = &SDL_TouchFingerEvent::operator=;
SDL_PenTipEvent& (SDL_PenTipEvent::*_58)(SDL_PenTipEvent&&) = &SDL_PenTipEvent::operator=;
SDL_PenMotionEvent& (SDL_PenMotionEvent::*_59)(SDL_PenMotionEvent&&) = &SDL_PenMotionEvent::operator=;
SDL_PenButtonEvent& (SDL_PenButtonEvent::*_60)(SDL_PenButtonEvent&&) = &SDL_PenButtonEvent::operator=;
SDL_DropEvent& (SDL_DropEvent::*_61)(SDL_DropEvent&&) = &SDL_DropEvent::operator=;
SDL_ClipboardEvent& (SDL_ClipboardEvent::*_62)(SDL_ClipboardEvent&&) = &SDL_ClipboardEvent::operator=;
SDL_SensorEvent& (SDL_SensorEvent::*_63)(SDL_SensorEvent&&) = &SDL_SensorEvent::operator=;
SDL_QuitEvent& (SDL_QuitEvent::*_64)(SDL_QuitEvent&&) = &SDL_QuitEvent::operator=;
SDL_UserEvent& (SDL_UserEvent::*_65)(SDL_UserEvent&&) = &SDL_UserEvent::operator=;
SDL_Event& (SDL_Event::*_66)(SDL_Event&&) = &SDL_Event::operator=;
SDL_HapticDirection& (SDL_HapticDirection::*_67)(SDL_HapticDirection&&) = &SDL_HapticDirection::operator=;
SDL_HapticConstant& (SDL_HapticConstant::*_68)(SDL_HapticConstant&&) = &SDL_HapticConstant::operator=;
SDL_HapticPeriodic& (SDL_HapticPeriodic::*_69)(SDL_HapticPeriodic&&) = &SDL_HapticPeriodic::operator=;
SDL_HapticCondition& (SDL_HapticCondition::*_70)(SDL_HapticCondition&&) = &SDL_HapticCondition::operator=;
SDL_HapticRamp& (SDL_HapticRamp::*_71)(SDL_HapticRamp&&) = &SDL_HapticRamp::operator=;
SDL_HapticLeftRight& (SDL_HapticLeftRight::*_72)(SDL_HapticLeftRight&&) = &SDL_HapticLeftRight::operator=;
SDL_HapticCustom& (SDL_HapticCustom::*_73)(SDL_HapticCustom&&) = &SDL_HapticCustom::operator=;
SDL_HapticEffect& (SDL_HapticEffect::*_74)(SDL_HapticEffect&&) = &SDL_HapticEffect::operator=;
SDL_hid_device_info& (SDL_hid_device_info::*_75)(SDL_hid_device_info&&) = &SDL_hid_device_info::operator=;
SDL_Locale& (SDL_Locale::*_76)(SDL_Locale&&) = &SDL_Locale::operator=;
SDL_MessageBoxButtonData& (SDL_MessageBoxButtonData::*_77)(SDL_MessageBoxButtonData&&) = &SDL_MessageBoxButtonData::operator=;
SDL_MessageBoxColor& (SDL_MessageBoxColor::*_78)(SDL_MessageBoxColor&&) = &SDL_MessageBoxColor::operator=;
SDL_MessageBoxColorScheme& (SDL_MessageBoxColorScheme::*_79)(SDL_MessageBoxColorScheme&&) = &SDL_MessageBoxColorScheme::operator=;
SDL_MessageBoxData& (SDL_MessageBoxData::*_80)(SDL_MessageBoxData&&) = &SDL_MessageBoxData::operator=;
SDL_RendererInfo& (SDL_RendererInfo::*_81)(SDL_RendererInfo&&) = &SDL_RendererInfo::operator=;
SDL_Vertex& (SDL_Vertex::*_82)(SDL_Vertex&&) = &SDL_Vertex::operator=;
SDL_Version& (SDL_Version::*_83)(SDL_Version&&) = &SDL_Version::operator=;
