// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;
using __CallingConvention = global::System.Runtime.InteropServices.CallingConvention;
using __IntPtr = global::System.IntPtr;

#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required
#pragma warning disable CS9084 // Struct member returns 'this' or other instance members by reference

namespace SDL3Sharp
{
    public unsafe partial class SDL
    {
        public partial struct __Internal
        {
            [SuppressUnmanagedCodeSecurity, DllImport("SDL3", EntryPoint = "?_m_prefetch@@YAXPEAX@Z", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern void MPrefetch(__IntPtr __P);

            [SuppressUnmanagedCodeSecurity, DllImport("SDL3", EntryPoint = "SDL_SwapFloat", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern float SwapFloat(float x);
        }

        public static void MPrefetch(__IntPtr __P)
        {
            __Internal.MPrefetch(__P);
        }

        /// <summary>Byte swap floating point number.</summary>
        public static float SwapFloat(float x)
        {
            var ___ret = __Internal.SwapFloat(x);
            return ___ret;
        }
    }
}
